### ISSUE TITLE
Enable the color scheme mode toggle?

### ISSUE THREAD

**Issue by pamelafox** [traceloop/docs#22]
I see that Mintlify has a mode toggle, that is disabled:

  "modeToggle": {
    "default": "dark",
    "isHidden": true
  },

I'm having a hard time reading the site with its dark mode colors, any chance that toggle could be enabled? I imagine this issue might be compatibility with the custom color overrides you've done. I'll try to mess with the HTML for now so that I can read it better.

**Comment by nirga** [comment]
@pamelafox thanks for flagging this! I'm actually not sure why I turned this off in the past 😅 
I verified that it looks fine so re-enabled it!
